# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Configuración de la sesión
    session:
        # Duración máxima de la sesión en segundos (300 segundos = 5 minutos)
        gc_maxlifetime: 300   # Caducidad de la sesión (5 minutos)
        cookie_lifetime: 300  # Duración de la cookie de la sesión en segundos (5 minutos)

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
